background            #202020
foreground            #d0d0d0
cursor                #d0d0d0
selection_background  #303030
color0                #fcc0cc
color8                #fcc0cc
color1                #fcc0c7
color9                #fcc0c7
color2                #fcc6c0
color10               #fcc6c0
color3                #fcdac0
color11               #fcdac0
color4                #fcebc0
color12               #fcebc0
color5                #d7fcc0
color13               #d7fcc0
color6                #cefcc0
color14               #cefcc0
color7                #c2fcc0
color15               #c2fcc0
selection_foreground  #f5ceec
background_opacity 0.65
shell fish
window_padding_width 2

# BEGIN_KITTY_FONTS
font_family      family='Bitstream Vera Sans Mono' style=Roman
bold_font        family='Bitstream Vera Sans Mono' style=Bold
italic_font      auto
bold_italic_font family='Bitstream Vera Sans Mono' style='Bold Oblique'
# END_KITTY_FONTS
